### PR TITLE
Login pop up Added to index.html

### PR DESCRIPTION
**Pull request by professorp**
Login Page successfully created.....
With Sign Up Option

### CODE REVIEW

**Comment by reverie-ss** [comment]
Great work buddy!
far better than before.
The UI is clean and beautiful!
1. Try to use the primary color of website as the login button color
2. The modal is not closing if clicked outside the window
3. SIgn Up and forgot password is outside the modal. Keep it inside!

**Comment by reverie-ss** [comment]
@professorp 
"Onclick on modal still have some errors so please resolve it.."
You can solve it. Use console.log() in developer mode to see where it is going wong. Otherwise google for "close modal on click outside it"

**Comment by professorp** [comment]
New errors are resolved now.

**Comment by reverie-ss** [comment]
- [ ] Try to use the primary color of website as the login button color
- [X] The modal is not closing if clicked outside the window
- [ ] Sign Up and forgot password is outside the modal. Keep it inside!

From the above only one is done!
Look into the other two.

1. Get primary color from main.css file : 

```
navigation {
    background-color: rgb(14, 180, 147);
}
```
2. Sign Up and forgot password is outside the modal. Keep it inside! 
I am attaching the screenshot.
Hint :- Use same container as of log in modal

screenshot 151

**Comment by reverie-ss** [comment]
@professorp I have merged the LogIn page of @smohapatra200!
Please integrate sign up page to the updated website.

**Comment by reverie-ss** [comment]
Well done!
Seems you have solved all the issues.

_Contribution guideline:_ 
Always make different PRs for different issues. (You have solved all the issues and sent a single PR)
This will make it easy to review for the maintainer. This will also get you more contributions for several issues instead of one.

The PR you have sent has conflicting issues. This issue has occurred because you have  not updated your repository. See your repository, it clearly states that, **"This branch is 5 commits ahead, 7 commits behind EnigmaVSSUT:master."**
First solve that. Open a PR for your repository and update it by merging.
Then go to your local repository and type `git pull` .

**Comment by professorp** [comment]
@reverie-ss 
"Always make different PRs for different issues. (You have solved all the issues and sent a single PR)
This will make it easy to review for the maintainer. This will also get you more contributions for several issues instead of one."
I will take care of this from the next time. This time I got confused about how to create a new PR.
And thanks for reminding me about the git pull.

**Comment by reverie-ss** [comment]
> I will take care of this from the next time. This time I got confused about how to create a new PR.
And thanks for reminding me about the git pull.

It's OK to get confused, you are a fast learner!

**Issues In This PR:**
1. The LogIn Window is already added. Do not make changes to it. Neither the login image nor the login modal. After` git pull` , just add the sign up functionality to it. Keep the log in window unchanged.
UI of sign up window should be similar to the UI of present LogIn window in website.


2. Upon, clicking on the sign up button a new modal is popped up. But the log in modal is not popped up.
screenshot 153
_It should work like : Click on sign up -> LogIn Modal Closed -> Sign Up Modal Opened_
3. Click outside to close **SignUp Module** is not working

P.S. Do not get demotivated because I am figuring out so many errors. This is just for your betterment to learn more. Happy learning! 👍

**Pull request closed without merging**
